## Adding numpy in Python

In [1]:
import numpy as np

## creating an array

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4=np.ones((3,3))
arr4              

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
arr6=np.arange(15)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr7=np.arange(2,20,5)
arr7

array([ 2,  7, 12, 17])

In [11]:
arr8=np.linspace(2,10,5)
arr8

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
arr9=arr5.copy()
arr9

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numpy array properties & it's attributes

In [4]:
import numpy as np

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2.shape

(2, 3)

In [8]:
arr9=np.array([[[1,2],[3,4],[6,7],[8,9]]])
arr9

array([[[1, 2],
        [3, 4],
        [6, 7],
        [8, 9]]])

In [9]:
arr9.shape

(1, 4, 2)

In [11]:
arr9.ndim #dimension

3

In [12]:
arr9.size

8

In [13]:
arr9.itemsize

4

In [15]:
arr9.dtype

dtype('int32')

In [16]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
arr5.dtype

dtype('float64')

In [18]:
arr9.astype('float') #we have changed the datatype of the array from int to float

array([[[1., 2.],
        [3., 4.],
        [6., 7.],
        [8., 9.]]])

# Numpy Array vs Python List

In [19]:
lista=range(100)
arr12=np.arange(100)

In [20]:
import sys #system

In [21]:
print(sys.getsizeof(87)*len(lista)) 

2800


In [22]:
print(arr12.itemsize*arr12.size)

400


In [23]:
import time

In [25]:
x=range(10000000)
y=range(10000000,20000000)

start_time=time.time()
c=[x+y for x,y in zip(x,y)]

print(time.time()-start_time)

1.4341278076171875


In [26]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)

start_time=time.time()
c=a+b

print(time.time()-start_time)

0.1394968032836914


# Indexing, Slicing & Iteration

In [29]:
arr13=np.arange(24).reshape(6,4)
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
arr13[:,3]

array([ 3,  7, 11, 15, 19, 23])

In [31]:
arr13[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [34]:
for i in arr13:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [35]:
for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
