## Adding numpy in Python

In [1]:
import numpy as np

## creating an array

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4=np.ones((3,3))
arr4              

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
arr6=np.arange(15)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr7=np.arange(2,20,5)
arr7

array([ 2,  7, 12, 17])

In [11]:
arr8=np.linspace(2,10,5)
arr8

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
arr9=arr5.copy()
arr9

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])