## Adding numpy in Python

In [1]:
import numpy as np

## creating an array

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4=np.ones((3,3))
arr4              

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
arr6=np.arange(15)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr7=np.arange(2,20,5)
arr7

array([ 2,  7, 12, 17])

In [11]:
arr8=np.linspace(2,10,5)
arr8

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
arr9=arr5.copy()
arr9

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numpy array properties & it's attributes

In [4]:
import numpy as np

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2.shape

(2, 3)

In [8]:
arr9=np.array([[[1,2],[3,4],[6,7],[8,9]]])
arr9

array([[[1, 2],
        [3, 4],
        [6, 7],
        [8, 9]]])

In [9]:
arr9.shape

(1, 4, 2)

In [11]:
arr9.ndim #dimension

3

In [12]:
arr9.size

8

In [13]:
arr9.itemsize

4

In [15]:
arr9.dtype

dtype('int32')

In [16]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
arr5.dtype

dtype('float64')

In [18]:
arr9.astype('float') #we have changed the datatype of the array from int to float

array([[[1., 2.],
        [3., 4.],
        [6., 7.],
        [8., 9.]]])